repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
    exclude: ^tests/test_rsc/invalid.yaml$
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.4
  hooks:
  - id: ruff
  - id: ruff-format

- repo: https://gitlab.com/smop/pre-commit-hooks
  rev: v1.0.0
  hooks:
  - id: check-poetry

- repo: https://github.com/RobertCraigie/pyright-python
  rev: v1.1.356
  hooks:
  - id: pyright

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.4
  hooks:
  - id: codespell

# NOTE: Removed as it's hella slow on commit
# - repo: https://github.com/twu/skjold
#   rev: v0.6.1
#   hooks:
#   - id: skjold
